### ISSUE TITLE
Collaboration Engine docs for V18+ have @Push on the wrong class

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/docs#105] opened 2021-01-13 10:43 UTC
https://vaadin.com/docs/v18/ce/tutorial.html#ce.tutorial.push
The `@Push` annotation should be on the `AppShellConfigurator` class, not the main layout, in V18 and later.

**Comment by pekam** [comment] 2021-01-13 10:46
Closing as a duplicate of https://github.com/vaadin/collaboration-engine-internal/issues/483

**Closed by pekam** 2021-01-13 10:46 UTC
