### ISSUE TITLE
Menu Bar Text visible through Usage & Styling Header

### ISSUE THREAD

**Issue by mrgreywater** [vaadin/docs#2355] opened 2023-04-06 12:51 UTC
I just noticed the MenuBar Button text is visible through the new Usage & Styling Header.

https://user-images.githubusercontent.com/2902403/230383559-690001e3-08cf-46b7-959f-fa900769824b.mp4

**Comment by jouni** [comment] 2023-04-06 14:29
I’m not able to reproduce this on macOS Safari, Chrome, or Firefox. What OS and browser are you using?

**Comment by mrgreywater** [comment] 2023-04-06 14:40
This page: https://vaadin.com/docs/latest/components/menu-bar
With Chrome Version 112.0.5615.50 (Official Build) (64-bit) running under Windows 11
The same happens with Firefox 111.0.1 (64-bit) running under Windows 11

Both running without extensions.

**Comment by jouni** [comment] 2023-04-11 10:24
> It only seems to happen to the java components, not when you select the typescript components.

Thanks, that was the missing piece of information. I can reproduce it now as well 👍

**Comment by jouni** [comment] 2023-04-11 10:33
The issue comes from these styles: https://github.com/vaadin/web-components/blob/main/packages/menu-bar/src/vaadin-menu-bar-button.js#L20-L23

When using Flow/Java, the additional `<vaadin-menu-bar-item>` element gets inserted. The TypeScript version just has a plain text node inside the `<vaadin-menu-bar-button>` element.

I have no memory why these styles are there in the first place (originally for slotted vaadin-context-menu-item elements). @web-padawan, or @tomivirkki, do you remember?

**Comment by jouni** [comment] 2023-04-11 10:34
Oh, there we go: https://github.com/vaadin/vaadin-menu-bar/commit/5bbdee8675d623ef4b2789ef763e86c3d5958292

**Comment by jouni** [comment] 2023-04-11 10:53
I pushed a fix/workaround to Design System Publisher (the documentation website builder), which should solve this.

**Closed** 2023-04-12 14:06 UTC
