### ISSUE TITLE
Styling issue with buttons

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/docs#673] opened 2021-08-02 11:10 UTC
The text of the starter download button in [Fusion tutorial](https://vaadin.com/docs/latest/fusion/tutorials/in-depth-course/project-setup) isn't showing.

![image](https://user-images.githubusercontent.com/42799254/127852555-67d18760-46c7-466e-b73b-017f06d56cdb.png)

**Comment by tarekoraby** [comment] 2021-08-09 08:17
There is a different styling issue with the download button in v20 branch: https://vaadin.com/docs/v20/fusion/tutorials/in-depth-course/project-setup

![image](https://user-images.githubusercontent.com/42799254/128677316-318328d0-ecdb-4554-a281-0eb164067442.png)

**Comment by jouni** [comment] 2021-08-18 05:15
This caused by Antlers styles clashing with DSP styles. On the index page, this is explicitly handled with custom CSS, which overrides the primary button text color (which is overridden by link styles in the first place).

**Comment by tarekoraby** [comment] 2021-08-20 18:01
There are other buttons with styling issues as well (I changed the ticket title accordingly). Two additional ones are

**Comment by jouni** [comment] 2021-08-21 20:46
All of these should be fixed in https://github.com/vaadin/docs/pull/695 (and other similar ones for the other branches), which are planned to be merged tomorrow.

**Comment by jouni** [comment] 2021-08-23 08:58
Fixed a couple of remaining ones I noticed, in addition to the ones listed before: 
- https://github.com/vaadin/docs/blob/v14/articles/flow/tutorials/in-depth-course/project-setup.adoc
- https://github.com/vaadin/docs/blob/latest/articles/flow/tutorials/in-depth-course/project-setup.adoc

All of the listed ones are fixed now.

**Closed by jouni** 2021-08-23 08:58 UTC
