### ISSUE TITLE
[popover] closes when selecting value

### ISSUE THREAD

**Issue by knoobie** [vaadin/docs#3678] opened 2024-09-17 08:33 UTC
### Description

When using a select or e.g. datepicker in a popover - the popover closes once a value is selected.

### Expected outcome

Popover stays open.

### Minimal reproducible example

https://vaadin.com/docs/latest/example?embed=popover-dropdown-field-wc.js&import=component/popover/popover-dropdown-field.ts,component/popover/react/popover-dropdown-field.tsx

### Environment

Vaadin version(s): latest docs
OS:

**Comment by web-padawan** [comment] 2024-09-17 09:15
Transferred to `docs` repo as the issue is specific to the `PopoverDropdownField` example:

- when selecting date in any of the pickers, `Select` is updated to reset value to empty string,
- the `Select` value change listener is then triggered and the Popover closes unexpectedly.

**Closed** 2024-09-18 17:30 UTC
