### ISSUE TITLE
Upload component can't be disabled

### ISSUE THREAD

**Issue by gsyjdcg** [vaadin/docs#2999] opened 2023-11-29 10:35 UTC
**The "Upload" component can't be disabled**

---

If you think this issue is important, add a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the community and maintainers prioritize this issue.

**Comment by rolfsmeds** [comment] 2023-11-29 13:36
Closing as duplicate of https://github.com/vaadin/web-components/issues/1278

**Closed by rolfsmeds** 2023-11-29 13:36 UTC
